# Generated by Django 5.2 on 2025-07-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='identification_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
