# Generated by Django 5.2 on 2025-07-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identification_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
