# Generated by Django 5.2 on 2025-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
