# Generated by Django 5.2 on 2025-04-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='encrypted_data',
            field=models.TextField(blank=True),
        ),
    ]
