# Generated by Django 5.2 on 2025-04-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('vote', 'Vote Cast'), ('election_created', 'Election Created'), ('vote_tally', 'Vote Tally'), ('user_registered', 'User Registered'), ('election_edit', 'Election Edited'), ('role_change', 'Role Changed')], max_length=50),
        ),
    ]
